# Copyright (c) 2020-2021, RTE (https://www.rte-france.com)
# Copyright (c) 2020-2021 RTE international (https://www.rte-international.com)
# See AUTHORS.txt
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
# SPDX-License-Identifier: MPL-2.0
# This file is part of the Let’s Coordinate project.

spring:
  profiles: docker
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/letsco?allowMultiQueries=true
    username: user
    password: userpwd
  kafka:
    bootstrap-servers: http://kafka:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/auth/realms/dev/protocol/openid-connect/certs

letsco:
  security:
    allowed-origins:
      - http://localhost:4200
      - http://letsco-front:4200
      - http://51.103.32.140:4200
      - https://51.103.32.140:4200

opfab:
  url:
    cardsPub: http://cards-publication:8080/cards

keycloak:
  server:
    url: http://keycloak:8080/auth
    realm: dev
    client-id: opfab-client
    client-secret: opfab-keycloak-secret