# Copyright (c) 2020-2021, RTE (https://www.rte-france.com)
# Copyright (c) 2020-2021 RTE international (https://www.rte-international.com)
# See AUTHORS.txt
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
# SPDX-License-Identifier: MPL-2.0
# This file is part of the Let’s Coordinate project.

server:
  port: 8088

spring:
  profiles: docker
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/letsco?allowMultiQueries=true
    username: user
    password: userpwd
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    open-in-view: false
    generate-ddl: false
  kafka:
    bootstrap-servers: http://kafka:9092
  liquibase:
    enabled: true
    drop-first: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/dev

logging:
  level:
    ROOT: INFO
    org.lfenergy.letscoordinate.backend: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
#  file: letsco_opensource.log
#  pattern:
#    console: '%d{yyyy-MM-dd HH:mm:ss} - %level - %logger{36} - %msg%n'
#    file: '%d{yyyy-MM-dd HH:mm:ss} - %level - %logger{36} - %msg%n'

letsco:
  timezone: "Europe/Paris"  # e.g: "Europe/London", "Europe/Paris", "Europe/Rome", "UTC", "UTC+1", "UTC-04:00", "GMT-5"
  input-file:
    dir: D:\_RTE_\tmp\input
    validation:
      accept-properties-ignore-case: true
      fail-on-unknown-properties: false

opfab:
  publisher: letsco_opensource
  url:
    cardsPub: http://cards-publication:8080/cards
  feed:
    # SERVICE A
    servicea_processsuccessful:
      title: " Service A process successful - {{processStep}}"
      summary: "{{businessDayFrom::dateFormat(dd/MM/yyyy)}}-{{businessDayTo::dateFormat(dd/MM/yyyy)}} (${letsco.timezone})"
    servicea_processfailed:
      title: " Service A process failed - {{processStep}}"
      summary: "{{businessDayFrom::dateFormat(dd/MM/yyyy)}}-{{businessDayTo::dateFormat(dd/MM/yyyy)}} (${letsco.timezone})"
    servicea_positivevalidation:
      title: " Service A {{noun}} - positive validation"
      summary: "{{businessDayFrom::dateFormat(dd/MM/yyyy)}}-{{businessDayTo::dateFormat(dd/MM/yyyy)}} (${letsco.timezone}) - {{sendingUser::eicToName()}}"
    servicea_positivevalidationwithwarnings:
      title: " Service A {{noun}} - positive validation with warnings"
      summary: "{{businessDayFrom::dateFormat(dd/MM/yyyy)}}-{{businessDayTo::dateFormat(dd/MM/yyyy)}} (${letsco.timezone}) - {{sendingUser::eicToName()}}"
    servicea_negativevalidation:
      title: " Service A {{noun}} - negative validation"
      summary: "{{businessDayFrom::dateFormat(dd/MM/yyyy)}}-{{businessDayTo::dateFormat(dd/MM/yyyy)}} (${letsco.timezone}) - {{sendingUser::eicToName()}}"
    # SERVICE B
    serviceb_processsuccessful:
      title: " Service B process successful - {{processStep}}"
      summary: "{{businessDayFrom::dateFormat(dd/MM/yyyy)}}-{{businessDayTo::dateFormat(dd/MM/yyyy)}} (${letsco.timezone})"
    serviceb_processfailed:
      title: " Service B process failed - {{processStep}}"
      summary: "{{businessDayFrom::dateFormat(dd/MM/yyyy)}}-{{businessDayTo::dateFormat(dd/MM/yyyy)}} (${letsco.timezone})"
    serviceb_positivevalidation:
      title: " Service B {{noun}} - positive validation"
      summary: "{{businessDayFrom::dateFormat(dd/MM/yyyy)}}-{{businessDayTo::dateFormat(dd/MM/yyyy)}} (${letsco.timezone}) - {{sendingUser::eicToName()}}"
    serviceb_positivevalidationwithwarnings:
      title: " Service B {{noun}} - positive validation with warnings"
      summary: "{{businessDayFrom::dateFormat(dd/MM/yyyy)}}-{{businessDayTo::dateFormat(dd/MM/yyyy)}} (${letsco.timezone}) - {{sendingUser::eicToName()}}"
    serviceb_negativevalidation:
      title: " Service B {{noun}} - negative validation"
      summary: "{{businessDayFrom::dateFormat(dd/MM/yyyy)}}-{{businessDayTo::dateFormat(dd/MM/yyyy)}} (${letsco.timezone}) - {{sendingUser::eicToName()}}"
  entityRecipients:
    sourceA_messageTypeNameA:
      notAllowed: sendingUser
      addRscs: true
    sourceA_messageTypeNameB:
      notAllowed: sendingUser
      addRscs: true

third-app:
  url: http://localhost:8081

keycloak:
  server:
    url: http://keycloak:8080/auth
    realm: dev
    client-id: opfab-client
    client-secret: opfab-keycloak-secret