# Copyright (c) 2020-2021, RTE (https://www.rte-france.com)
# Copyright (c) 2020-2021 RTE international (https://www.rte-international.com)
# See AUTHORS.txt
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
# SPDX-License-Identifier: MPL-2.0
# This file is part of the Let’s Coordinate project.

spring:
  application:
    name: cards-publication
  deserializer:
    value:
      delegate:
        class: io.confluent.kafka.serializers.KafkaAvroDeserializer
  #        class: org.opfab.cards.publication.kafka.consumer.KafkaAvroWithoutRegistryDeserializer
  serializer:
    value:
      delegate:
        class: io.confluent.kafka.serializers.KafkaAvroSerializer
#        class: org.opfab.cards.publication.kafka.producer.KafkaAvroWithoutRegistrySerializer
# uncomment kafka.consumer.group-id to enable Kafka
#  kafka:
#    consumer:
#      group-id: opfab-command

opfab:
  kafka:
    topics:
      card:
        topicname: opfab
      response-card:
        topicname: opfab-response
    schema:
      registry:
        url: http://localhost:8081

# WARNING - You shoud replace localhost with the real IP , as locahost related to IP internal to docker
externalRecipients-url: "{\
           letsco_opensource: \"http://172.30.0.1/letsco/api/v1/coordination\" \
           }"
checkAuthenticationForCardSending: false