# Copyright (c) 2020-2021, RTE (https://www.rte-france.com)
# Copyright (c) 2020-2021 RTE international (https://www.rte-international.com)
# See AUTHORS.txt
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
# SPDX-License-Identifier: MPL-2.0
# This file is part of the Let’s Coordinate project.

server:
  forward-headers-strategy: framework
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  security:
    provider-url: http://keycloak:8080
    provider-realm: dev
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${spring.security.provider-url}/auth/realms/${spring.security.provider-realm}/protocol/openid-connect/certs
  data:
    mongodb:
      database: operator-fabric
      uri: mongodb://root:password@mongodb:27017/operator-fabric?authSource=admin&authMode=scram-sha1
security:
  basic:
    enabled: false

operatorfabric:
  businessLogActivated: true
  servicesUrls:
    users: "http://172.19.0.1:2103"

### activate the following if you want to the groups or entities to come from the token and not mongo DB
#  security:
#    jwt:

### activate the folLowing if you want the entities of the user to come from the token and not mongoDB
### entitiesIdClaim is the name of the field in the token
#      entitiesIdClaim : entitiesId
#      gettingEntitiesFromToken: true
###

### activate the following if you want the groups of the user to come from the token and not mongoDB
#      groups:
#        mode: JWT
#        rolesClaim:
#          rolesClaimStandard:
#            - path: "ATTR1"
#            - path: "ATTR2"
#          rolesClaimStandardArray:
#            - path: "resource_access/opfab-client/roles"
#          rolesClaimStandardList:
#            - path: "groups"
#              separator: ";"
#          rolesClaimCheckExistPath:
#            - path: "resource_access/AAA"
#              roleValue: "roleAAA"
#            - path: "resource_access/BBB"
#              roleValue: "roleBBB"
###
message: common message
management:
  endpoints:
    web:
      exposure:
        include: '*'